name: Publish to Registry
on:    
  release:
      types: [published]
  push:
    branches:
      - main
      - docker-testing
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Release
      run: echo "${{ github.event.release.tag_name }}""
    - name: Publish to Registry
      # run: echo "${{ github.event.release.tag_name }}"
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: nsglobusautobuilds/publish-test
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ github.event.release.tag_name }}"
        workdir: single-user
